mysite/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mysite3/mysite3/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('shop/', include('shop.urls')),
    path('admin/', admin.site.urls),
]

mysite3/shop/urls.py
from django.urls import path  # , include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views


app_name = 'shop'
#, kwargs=kwargs1  kwargs1={"page": 1, "size": 1}
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:product_id>/', views.DetailView.as_view(), name='detail'),  #  views.detail
    path('photos/<int:product_id>/', views.add_photos, name='photos'), # PhotosProductView.as_view()
    path('<int:category_id>/', views.CategoryView.as_view(), name='category'),
    path('<int:category_id>/page<int:page>/', views.CategoryView.as_view(), name='category'),
    path('<int:category_id>/page<int:page>/size<int:size>/', views.CategoryView.as_view(), name='category'),
    path('login/', views.LoginGuestView.as_view(), name='login'),
    path('register/', views.RegistrationGuestView.as_view(), name='register'),
    path('login/cart/', views.ProductsCartView.as_view(), name='cart'),
    path('logout/', views.log_out, name='log_out'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('ajax/validate_username/', views.validate_username, name='validate_username'),
    path('ajax/login/', views.log_in, name='ajax_login'),
    path('ajax_order_check/', views.ajax_order_check, name='ajax_order_check'),
    path('order/<int:order_id>/', views.OrderView.as_view(), name='order'),
    path('orders/', views.orders, name='orders'),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite3/shop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Tовары относятся к разным категориям.
class Category(models.Model):
    name = models.CharField(unique=True, max_length=200)

    def __str__(self):
        return self.name


class Category_photo(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='category')

    def __str__(self):
        return self.photo.name


# Поставщики: python manage.py runserver
class Provider(models.Model):
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length=24)  #  IntegerField(default=0)
    email = models.EmailField(null=True)
    address = models.CharField(max_length=400, default='')

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=200, unique=True, default='')

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True) # model
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    description = models.CharField(max_length=4000, default='')
    quantity = models.IntegerField(default=1)
    price = models.IntegerField(null=False)
    production_date = models.DateField(blank=True, null=True)#(default=timezone.now) # incoming
    providers = models.ManyToManyField(Provider)
    reserved = models.IntegerField(default=0)

    def __str__(self):
        return self.name


class Photo(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='photos') # shop/static/shop/photos

    def __str__(self):
        return self.photo.name


class Mini_photo(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    mini = models.ImageField(upload_to='mini_photos')

    def __str__(self):
        return self.mini.name


class Guest(User):
    is_superuser = False
    is_staff = False

    def __str__(self):
        return self.username


class Product_in_cart(models.Model):
    product  = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    guest = models.ForeignKey(Guest, on_delete=models.CASCADE)

    def __str__(self):
        return self.product.name


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, default='', null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.CharField(max_length=4000, default='')

    def __str__(self):
        return self.content


class Order(models.Model):
    guest = models.ForeignKey(Guest, on_delete=models.PROTECT)
    date = models.DateTimeField(default=timezone.now)
    coming_date = models.DateField(blank=True, null=True)
    payed = models.BooleanField(default=False)
    received  = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Ordered_product(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField(null=False)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

    def __str__(self):
        return self.product.name

# class Payment_requisites(models.Model):

mysite3/shop/forms.py
from django import forms
from .models import *


class ImageFieldForm(forms.Form):
    images = forms.ImageField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))
    mini = forms.ImageField(label='Mini images', required=False, widget=forms.ClearableFileInput(attrs={'multiple': True}))


class LoginForm(forms.Form):
    username = forms.CharField(label='Имя:', max_length=30)
    password = forms.CharField(label='Пароль:', max_length=30)


class RegisterForm(forms.Form):
    first_name = forms.CharField(label='Имя: ', max_length=20)
    username = forms.CharField(label='Имя: ', max_length=30)
    password = forms.CharField(label='Пароль: ', max_length=30)
    email = forms.EmailField(required=True)


class SearchForm(forms.Form):
    c_list = [('all', 'Все категории')]
    c_list.extend([(cat.name, cat.name) for cat in Category.objects.all()])
    CATEGORY_CHOICES = (c_list)
    SEARCH_CHOICES = (('name','Модель',),('manufacturer', 'Марка',),
                      ('description','Описание',),)
    ORDER_CHOICES = (('price_down','По убыванию цены',),('price_up', 'По возрастанию цены',),
                      ('alph','По алфавиту',),('alph_back','Алфавит наоборот',))
    order = forms.ChoiceField(required=False, label='Сортировать:', widget=forms.RadioSelect,
                              choices=ORDER_CHOICES)
    where = forms.ChoiceField(required=False, label='В каком поле искать:', widget=forms.RadioSelect, choices=SEARCH_CHOICES)
    categories = forms.MultipleChoiceField(initial = ('all', 'Все категории'), label='Категория поиска:',
        required=True,
        widget=forms.CheckboxSelectMultiple,
        choices=CATEGORY_CHOICES,
    )
    search = forms.CharField(required=False, label='Что искать:', max_length=30)



class ProductInCartForm(forms.Form):
    quantity = forms.IntegerField(label='Заказать:', min_value = 0, initial = 0)


class AddCommentStaffForm(forms.Form):
    name = forms.CharField(label='Имя: ', max_length=30, required=True)
    content = forms.CharField(widget=forms.Textarea, max_length=4000, required=True, label='')


class AddCommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea, max_length=4000, required=True, label='')

# class CartForm(forms.ModelForm):
#
#     class Meta:
#         model = Product_in_cart
#         fields = ['product', 'quantity', 'guest'] # , 'guest'

mysite3/shop/views.py
from .models import *
from .forms import *
from django.http import HttpResponse, HttpResponseNotFound
from django.views import View, generic
from django.http import HttpResponseBadRequest, HttpResponseForbidden, HttpResponseRedirect
from django.core.paginator import Paginator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.views.generic.edit import FormView
from django.core.validators import validate_image_file_extension
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_http_methods
from django.http import JsonResponse
from django.forms import modelformset_factory


nginx = "http://127.0.0.1:80"
Page_Size = 3


def get_mini(prod):
    mini = Mini_photo.objects.filter(product=prod)
    if mini:
        mini = nginx + str(mini.first().mini.url)
    else:
        mini = None
    return mini


def get_product_str(prod):
    mini = get_mini(prod)
    data = {"category" : prod.category.name, "name": prod.name, "id": prod.id, "price": prod.price,
                "mini": mini,"production_date": prod.production_date.strftime('%Y.%m.%d')} # .strftime('%Y.%m.%d') -%H:%M:%S
    return data


def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse("shop:index"))


def log_in(request): #  *args, **kwargs
    form = LoginForm(request.POST)
    if form.is_valid():
        user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
        if user is not None:
            login(request, user)
            try:
                g = Guest.objects.get(username=user.username)
            except Guest.DoesNotExist:
                content = "You are login " + user.username + '. But to purchase goods you need to register as a guest.'
                return HttpResponse(content)
        else:
            return HttpResponseForbidden('You must register first.')
        return HttpResponseRedirect(reverse('shop:cart'))
    else:
        return LoginForm()


class LoginGuestView(FormView):
    form_class = LoginForm
    template_name = 'shop/login.html'
    success_url = reverse_lazy('shop:cart')

    def post(self, request):
        return log_in(request)


class SearchView(FormView):
    form_class = SearchForm()
    template_name = 'shop/search.html'
    success_url = reverse_lazy('shop:search')

    def get(self, request):
        form = SearchForm()
        return render(request, self.template_name, {"form": form, "find": False})

    def post(self, request):
        form = SearchForm(request.POST)
        if not form.is_valid():
            return render(request, self.template_name, {"form": form, "find": False})
        categories = form.cleaned_data['categories']
        search = form.cleaned_data['search']
        where = form.cleaned_data['where']
        order = form.cleaned_data['order']
        if "all" in categories:
            res = False
            if where == "name":
                res = Product.objects.filter(name__contains=search)
            elif where == "manufacturer":
                res = Product.objects.filter(manufacturer__name__contains=search)
            elif where == "description":
                res = Product.objects.filter(description__contains=search)
            if res:
                if order == 'alph':
                    res = res.order_by('name')
                elif order == 'alph_back':
                    res = res.order_by('-name')
                elif order == 'price_up':
                    res = res.order_by('price')
                elif order == 'price_down':
                    res = res.order_by('-price')
            elif order == 'alph':
                res = Product.objects.order_by('name')
            elif order == 'alph_back':
                res = Product.objects.order_by('-name')
            elif order == 'price_up':
                res = Product.objects.order_by('price')
            elif order == 'price_down':
                res = Product.objects.order_by('-price')
        else:
            res = Product.objects.none()
            for cat in categories:
                data = None
                c = get_object_or_404(Category, name=cat)
                if where == "name":
                    data = Product.objects.filter(category=c).filter(name__contains=search)
                elif where == "manufacturer":
                    data = Product.objects.filter(category=c).filter(manufacturer__name__contains=search)
                elif where == "description":
                    data = Product.objects.filter(category=c).filter(description__contains=search)
                if data:
                    if order == 'alph':
                        data = data.order_by('name')
                    elif order == 'alph_back':
                        data = data.order_by('-name')
                    elif order == 'price_up':
                        data = data.order_by('price')
                    elif order == 'price_down':
                        data = data.order_by('-price')
                elif order == 'alph':
                    data = Product.objects.filter(category=c).order_by('name')
                elif order == 'alph_back':
                    data = Product.objects.filter(category=c).order_by('-name')
                elif order == 'price_up':
                    data = Product.objects.filter(category=c).order_by('price')
                elif order == 'price_down':
                    data = Product.objects.filter(category=c).order_by('-price')
                res |= data

        form = SearchForm()
        return render(request, self.template_name, {"form": form, "find": res, "where": where})


class ProductsCartView(FormView):
    form_class = modelformset_factory(Product_in_cart, fields=('quantity',), extra=0, can_delete=True)
    template_name = 'shop/cart.html'
    success_url = reverse_lazy('shop:cart')

    def get(self, request):
        user = request.user
        if not user.is_authenticated:
            return HttpResponseRedirect(reverse('shop:login'))
        if user.is_staff:
            return HttpResponseRedirect(reverse('admin:index'))
        g = get_object_or_404(Guest, username=user.username)
        CartFormSet = self.get_form_class() # , can_order=True
        cart = Product_in_cart.objects.filter(guest=g).order_by('id')
        formset = CartFormSet(queryset = cart) # .filter(quantity__gt=0)
        context = {"formset": formset, "name": g.username, "nginx": nginx + '/media/', "cart_full": True if cart else False} # , 'cart': data
        return render(request, self.template_name, context)


    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return HttpResponseRedirect(reverse('shop:login'))
        if user.is_staff:
            return HttpResponseRedirect(reverse('admin:index'))
        guest = get_object_or_404(Guest, username=user.username)
        CartFormSet = self.get_form_class()
        initial = CartFormSet(queryset=Product_in_cart.objects.filter(guest=guest).order_by('id'))
        formset = CartFormSet(request.POST, initial=initial) # form = CartForm(request.POST, instance=prod)
        if formset.is_valid():
            formset.save()
            good = guest.product_in_cart_set.filter(quantity__gt=0)
            if not good:
                return HttpResponseRedirect(reverse('shop:cart'))
            ord = Order.objects.create(guest=guest)
            for g in good:
                prod = get_object_or_404(Product, id=g.product.id)
                Ordered_product.objects.create(order = ord, product=prod, quantity=g.quantity)
                prod.reserved += g.quantity
                prod.save()
                g.delete()
            return HttpResponseRedirect(reverse('shop:order', args=(ord.pk,))) # cart'))
        else:
            return HttpResponseRedirect(reverse('shop:cart'))


@require_http_methods(["POST"])
def ajax_order_check(request):
    user = request.user
    g = get_object_or_404(Guest, username=user.username)
    CartFormSet = modelformset_factory(Product_in_cart, fields=('quantity',), extra=0, can_delete=True)
    initial = CartFormSet(queryset=Product_in_cart.objects.filter(guest=g).order_by('id'))
    formset = CartFormSet(request.POST, initial=initial)
    error = False
    # if formset.is_valid():
    for form in formset:
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            id = form.instance.product.id
            prod_old = get_object_or_404(Product, id=id)
            free = prod_old.quantity - prod_old.reserved
            if free < quantity:
                error = "В наличии " + prod_old.__str__()
                if free == 0:
                    error += " нет."
                else:
                    error += "  есть только " + str(free) + " шт."
    return JsonResponse({"error": error})


@require_http_methods(["GET"])   # POST
def orders(request):
    user = request.user
    if not user.is_authenticated:
        return HttpResponseRedirect(reverse('shop:login'))
    if user.is_staff:
        return HttpResponseRedirect(reverse('admin:index'))
    guest = get_object_or_404(Guest, username=user.username)
    orders = guest.order_set.all()
    return render(request, 'shop/orders.html', {"orders": orders, "nginx": nginx + '/media/'})


class OrderView(View):
    template_name = 'shop/order.html'

    def get(self, request, order_id):
        user = request.user
        if not user.is_authenticated:
            return HttpResponseRedirect(reverse('shop:login'))
        if user.is_staff:
            return HttpResponseRedirect(reverse('admin:index'))
        order = Order.objects.get(pk=order_id)

mysite3/shop/templates/shop/base.html
{% load static %}<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Default Title{% endblock %}</title>

    {% block stylesheet %}{% endblock %}
  </head>
  <body>
    <header>

    </header>
    <main>
      {% block content %}
      {% endblock %}
    </main>
    <footer>

    </footer>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

    {% block javascript %}{% endblock %}
  </body>
</html>

mysite3/shop/templates/shop/cart.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
</head>
<body>
<br>
<table width="80%">
<tr><td>
    <a href="{% url 'shop:orders' %}">Ваши заказы.</a>
    </td><td style="text-align: right;">
    <a href="{% url 'shop:index' %}">Вернуться на главную страницу.</a>
</td></tr>
</table>

<br>
<h3>Здравствуйте {{ name }}</h3>
<p>В вашей корзине:</p>
{% if cart_full %}
        <form method="post" id="FORM-1" check_num="{% url 'shop:ajax_order_check' %}">
        {% csrf_token %}
    {{ formset.management_form }}
    {% for form in formset %}
        <ul>
        <li><img src="{{ nginx }}{{ form.instance.product.mini_photo_set.first }}"/>
            {{ form.instance.product.manufacturer }}
            {{ form.instance.product }}
            Количество:{{ form.quantity }}
            {% if formset.can_delete %}
                Удалить{{ form.DELETE }}
            {% endif %}
            {{ form.id }}
        </li>
        </ul>
    {% endfor %}
 <button type="submit" id="btn1"><h1>Заказать</h1></button></form>

{% else %}
    <p>Нет продуктов.</p>
{% endif %}

<h4 id="alert1"></h4>

{% block javascript %}
  <script>
    $("#FORM-1").change(function () {
      var form = $('#FORM-1');
      $.ajax({
        url: form.attr("check_num"),
        type: form.attr('method'),
        data: form.serialize(),
        dataType: 'json',
        success: function (data) {
          if (data.error) {
            $("#alert1").text(data.error);
            $('#btn1').hide();
          }
          else{
	    $("#alert1").text('');
            $('#btn1').show();
          }
        }
      });
    });
  </script>
{% endblock %}
</body>
</html>

mysite3/shop/templates/shop/category.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> {{ category }}:</h1>
<ul>
    {% for p in data %}
        <li><img src="{{ p.mini }}"/><a href="{% url 'shop:detail' p.id %}">{{ p.name }}: цена: {{ p.price }}, произведено: {{ p.production_date }}</a></li>
    {% endfor %}
</ul>
<p>
    {% for p in pages %}
        <a href="{% url 'shop:category'  category_id=category_id page=p %}">{{ p }}</a> |
    {% endfor %}
</p>
</body>
</html>

mysite3/shop/templates/shop/detail.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style type="text/css">
        div{   width: 85%;
					border-left: 3px solid black;
					border-top: 3px solid black;
					margin-left: 20px; margin-right: 20px; padding-left: 20px;}
    </style>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
</head>
<body>
{% if id %}
    <a href="{% url 'shop:photos' id %}">Добавить фотографии.</a>
{% else %}
    <form action="" method="post">
    {% csrf_token %}
    {{ cart_form }}
    <input type="submit" value="Добавить в корзину" />
    </form>
{% endif %}
<h3>{{ name }} </h3>
<p>{{ category }},</p>
<p>Цена: {{ price }},</p>
<p>Произведено: {{ production_date }}</p>
<p>Описание: {{ description }}</p>
    {% for image in images %}
        <img src="{{ image }}" alt="{{ image }}"/>
    {% endfor %}
<br>

    {% if add_com_form %}
    <p>Добавить комментарий:</p>
    <form action="" method="post">
         {% csrf_token %}
         {{ add_com_form }}
        <input type="submit" value="Отправить" />
    </form>
    {% endif %}

<br>
    {% for com in comments %}
    <div>
        <p>Комментарий {{ com.name}}:</p>
        <p>{{ com.content }}</p>
    </div>
    {% endfor %}
</body>
</html>

mysite3/shop/templates/shop/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div style="position:relative; top: 37px; left: 1%;">
    <a href="{% url 'shop:search' %}">Поиск</a>
</div>

<div class="enter_form" style="position:relative; top: 20px; left: 50%;">
{% if user %}
    <p>Здравствуйте, {{ user.username }}.
    {% if user.is_staff %}
        <a href="{% url 'admin:index' %}">Войти на страницу администрирования.</a></p>
    {% else %}
        <a href="{% url 'shop:cart' %}">Посмотреть корзину.</a></p>
    {% endif %}
{% else %}
    <a href="{% url 'shop:register' %}">Зарегестрироваться.</a>

    <form check_action="{% url 'shop:ajax_login' %}" method="post" id="FORM-1">
    {% csrf_token %}
    {{ form }}
    <button type="button" id="btn1">Войти</button>
    </form>
{% endif %}
</div>

<div style="position:relative; top: 20px; left: 50%;">
    <p>
    <table width="40%">
				<tr>
				   <td id="alert1"></td>
				   <td><a id="alert2" href="{% url 'shop:cart' %}"></a></td>
				 </tr>
    </table>
    </p>
</div>
<br>
<div style="position:absolute; top: 10%;">
    <h4> Категории товаров:</h4>
    <ul>
    {% for cat in data %}
        <li><img src="{{ cat.image }}"/><a href="{% url 'shop:category' cat.id %}">{{ cat.name }}</a></li>
    {% endfor %}
    </ul>
</div>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
{% block javascript %}
<script>
    $('#btn1').click(function () {
        var frm = $('#FORM-1');
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('check_action'),
            data: frm.serialize(),
            dataType: 'json',
            success: function (data) {
                if (data.error) {
                    $("#alert1").text(data.error);
                }
                else{
                    $(".enter_form").fadeOut(300)
                                    .hide();
	                $("#alert1").text(data.hello).fadeIn(800);
	                $("#alert2").text("Посмотреть корзину.").fadeIn(800);

                }
            }
        });
    });
</script>
{% endblock %}
</body>
</html>

mysite3/shop/templates/shop/login.html
{% extends 'shop/base.html' %}

{% block javascript %}
<script>
    $('#btn1').click(function () {
        var frm = $('#FORM-1');
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('check_action'),
            data: frm.serialize(),
            dataType: 'json',
            success: function (data) {
                if (data.error) {
                    $("#alert1").text(data.error);
                }
                else{
	                $("#alert1").text(data.hello);
	                $("#alert2").text("Перейти на главную страницу.");
                    $('.enter_form').hide();
                }
            }
        });
    });
</script>
{% endblock %}


{% block content %}
<div class="enter_form">
    <p>Надо войти, чтобы заказывать товары.</p>
    <form method="post" id="FORM-1" check_action="{% url 'shop:ajax_login' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="button" id="btn1">Войти</button>
    </form>
</div>
<h4 id="alert1"></h4>
<a id="alert2" href="{% url 'shop:index' %}"></a>

<img src="http://127.0.0.1/media/big.png" width="70%" height="70%" style="position:absolute; bottom: 20px; left: 175px;"/>
{% endblock %}

mysite3/shop/templates/shop/order.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>{{ order.guest }}, вы можете оплатить заказ № {{ order }} по следующим ниже реквизитам.</p>
    <p>{{ order.date }}</p>
    {% for prod in order.ordered_product_set.all %}
    <ul>
        <li>
            <p><img src="{{ nginx }}{{ prod.product.mini_photo_set.first }}"/>
                {{ prod.product.manufacturer }}</p>
            <p>{{ prod.product }}</p>
            <p>Количество: {{ prod.quantity }}</p>
        </li>
    </ul>
    {% endfor %}
<h3>Реквизиты: </h3>
<p>БИК: 2241343645645645</p>
<p>ИНН: 452454634563435</p>
</body>
</html>

mysite3/shop/templates/shop/orders.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<table width="80%">
<tr><td>
    <p>Ваши заказы:</p>
    </td><td style="text-align: right;">
    <a href="{% url 'shop:index' %}">Вернуться на главную страницу.</a>
</td></tr>
</table>


    {% for order in orders %}
    <ul>
        <li>
            <p><a href="{% url 'shop:order' order.id %}">Заказ № {{ order.id }}</a></p>
            {% for prod in order.ordered_product_set.all %}
                <p><img src="{{ nginx }}{{ prod.product.mini_photo_set.first }}"/>
                    {{ prod.product.manufacturer }}
                    , {{ prod.product }}
                    , Количество: {{ prod.quantity }}
                </p>
            {% endfor %}
        </li>
    </ul>
    {% endfor %}
</body>
</html>

mysite3/shop/templates/shop/photos.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form enctype="multipart/form-data" method="post" action="">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
<h3>Mini images:</h3>
    {% for image in minis %}
        <img src="{{ image }}" alt="{{ image }}"/>
    {% endfor %}
<h3>Images:</h3>
    {% for image in images %}
        <img src="{{ image }}" alt="{{ image }}"/>
    {% endfor %}
</body>
</html>

mysite3/shop/templates/shop/register.html
{% extends 'shop/base.html' %}

{% block javascript %}
  <script>
    $("#id_username").change(function () {
      var form = $(this).closest("form");
      $.ajax({
        url: form.attr("data-validate-username-url"),
        data: form.serialize(),
        dataType: 'json',
        success: function (data) {
          if (data.is_taken) {
            $("#alert1").text(data.error_message);
            $('#btn1').hide();
          }
          else{
	        $("#alert1").text('');
            $('#btn1').show();
          }
        }
      });
    });
  </script>
{% endblock %}

{% block content %}
<h4> Регистрация:</h4>
  <form method="post" data-validate-username-url="{% url 'shop:validate_username' %}">
    {% csrf_token %}
    {{ form }}
    <button type="submit" id="btn1">Зарегистрироваться</button>
  </form>
<h4 id="alert1"></h4>

<img src="http://127.0.0.1/media/big.png" width="70%" height="70%" style="position:absolute; bottom: 20px; left: 175px;"/>
{% endblock %}

mysite3/shop/templates/shop/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table width="80%">
<tr><td>
    <h4 style="text-align: center;">Поиск</h4>
    </td><td style="text-align: right;">
    <a href="{% url 'shop:index' %}">Вернуться на главную страницу.</a>
</td></tr>
</table>
<form method="post">
{% csrf_token %}
{{ form.as_table }}
<input type="submit" value="Найти" />
</form>
{% if find %}
<ul>
    {% for p in find %}
    <li>
        <p>{{ p.manufacturer }}, <a href="{% url 'shop:detail' p.id %}">{{ p }}</a></p>
        {% if where == "description" %}
            <p>{{ p.description }}</p>
        {% endif %}
    </li>
    {% endfor %}
</ul>
{% endif %}
</body>
</html>